# services:
#   backend:
    
#     build: ./backend
#     ports:
#       - 5000:5000
#     volumes:
#       - ./backend:/backend
#   frontend:
#     image: frontend-angular
#     build: ./frontend
#     volumes:
#       - ./frontend/src:/frontend/src # for watching files
#     ports:
#       - 4200:4200

version: "3"
services:
  frontend:
    image: frontend-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    volumes:
      - ./frontend/src:/frontend/src # for watching files
    ports:
      - "4200:4200"
  backend:
    image: backend-flask
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    volumes:
        - ./backend:/backend # for watching files
    ports:
      - "5000:5000" # if changed, please change port in `frontend/proxy.conf.dev.json`
